# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Statistik(QtWidgets.QWidget):
    def setupUi(self, Statistik):
        Statistik.setObjectName("Statistik")
        Statistik.resize(800, 450)

        self.menuOption = QtWidgets.QWidget(Statistik)
        self.menuOption.setObjectName("menuOption")
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menuOption)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.Income = QtWidgets.QFrame(self.menuOption)
        self.Income.setGeometry(QtCore.QRect(190, 10, 171, 111))
        self.Income.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Income.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Income.setObjectName("Income")
        
        self.incomeInfo = QtWidgets.QLabel(self.Income)
        self.incomeInfo.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.incomeInfo.setObjectName("incomeInfo")
        
        self.IncomeValue = QtWidgets.QLabel(self.Income)
        self.IncomeValue.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.IncomeValue.setObjectName("IncomeValue")
        
        self.Outcome = QtWidgets.QFrame(self.menuOption)
        self.Outcome.setGeometry(QtCore.QRect(374, 10, 181, 111))
        self.Outcome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Outcome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Outcome.setObjectName("Outcome")
        
        self.outcomeInfo = QtWidgets.QLabel(self.Outcome)
        self.outcomeInfo.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.outcomeInfo.setObjectName("outcomeInfo")
        self.outcomeValue = QtWidgets.QLabel(self.Outcome)
        self.outcomeValue.setGeometry(QtCore.QRect(40, 50, 81, 16))
        self.outcomeValue.setObjectName("outcomeValue")
        
        self.Statistic = QtWidgets.QFrame(self.menuOption)
        self.Statistic.setGeometry(QtCore.QRect(190, 140, 361, 301))
        self.Statistic.setObjectName("Statistic")

        self.frameStatistic = QtWidgets.QFrame(self.Statistic)
        self.frameStatistic.setGeometry(QtCore.QRect(10, 10, 341, 281))
        self.frameStatistic.setObjectName("frameStatistic")
        
        self.statisticOption = QtWidgets.QComboBox(self.Statistic)
        self.statisticOption.setGeometry(QtCore.QRect(330, 10, 20, 22))
        self.statisticOption.setObjectName("statisticOption")
        self.statisticOption.addItem("")
        self.statisticOption.addItem("")
        self.statisticOption.addItem("")
        self.statisticOption.addItem("")
        self.statisticOption.addItem("")
        self.statisticOption.addItem("")
        
        self.SliderButton = QtWidgets.QWidget(self.Statistic)
        self.SliderButton.setGeometry(QtCore.QRect(210, 10, 111, 21))
        self.SliderButton.setObjectName("SliderButton")
        
        self.prevButton = QtWidgets.QPushButton(self.SliderButton)
        self.prevButton.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.prevButton.setObjectName("prevButton")
        
        self.nextButton = QtWidgets.QPushButton(self.SliderButton)
        self.nextButton.setGeometry(QtCore.QRect(90, 0, 20, 23))
        self.nextButton.setObjectName("nextButton")

        self.sliderType = QtWidgets.QComboBox(self.SliderButton)
        self.sliderType.setGeometry(QtCore.QRect(20, 0, 69, 22))
        self.sliderType.setObjectName("sliderType")
        self.sliderType.addItem("")
        self.sliderType.addItem("")
        self.sliderType.addItem("")
        self.sliderType.addItem("")

        self.statisticInfo = QtWidgets.QLabel(self.Statistic)
        self.statisticInfo.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.statisticInfo.setTextFormat(QtCore.Qt.RichText)
        self.statisticInfo.setObjectName("statisticInfo")
        
        self.barChart = QtWidgets.QGraphicsView(self.Statistic)
        self.barChart.setGeometry(QtCore.QRect(10, 40, 341, 251))
        self.barChart.setObjectName("barChart")
        
        self.timeInfo = QtWidgets.QLabel(self.Statistic)
        self.timeInfo.setGeometry(QtCore.QRect(150, 50, 47, 13))
        self.timeInfo.setTextFormat(QtCore.Qt.RichText)
        self.timeInfo.setObjectName("timeInfo")
        
        self.Summary = QtWidgets.QFrame(self.menuOption)
        self.Summary.setGeometry(QtCore.QRect(560, 230, 229, 206))
        self.Summary.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Summary.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Summary.setObjectName("Summary")
        
        self.summaryInfo = QtWidgets.QLabel(self.Summary)
        self.summaryInfo.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.summaryInfo.setObjectName("summaryInfo")
        
        self.newBalance = QtWidgets.QLabel(self.Summary)
        self.newBalance.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.newBalance.setObjectName("newBalance")
        
        self.prevBalance = QtWidgets.QLabel(self.Summary)
        self.prevBalance.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.prevBalance.setObjectName("prevBalance")
        
        self.prevValue = QtWidgets.QLabel(self.Summary)
        self.prevValue.setGeometry(QtCore.QRect(70, 90, 121, 16))
        self.prevValue.setObjectName("prevValue")
        
        self.newValue = QtWidgets.QLabel(self.Summary)
        self.newValue.setGeometry(QtCore.QRect(70, 150, 121, 16))
        self.newValue.setObjectName("newValue")
        
        self.changeValue = QtWidgets.QLabel(self.Summary)
        self.changeValue.setGeometry(QtCore.QRect(90, 180, 71, 16))
        self.changeValue.setObjectName("changeValue")
        
        self.pieChart = QtWidgets.QFrame(self.menuOption)
        self.pieChart.setGeometry(QtCore.QRect(560, 10, 231, 211))
        self.pieChart.setObjectName("pieChart")
        
        self.pieChartOption = QtWidgets.QComboBox(self.menuOption)
        self.pieChartOption.setGeometry(QtCore.QRect(760, 20, 20, 22))
        self.pieChartOption.setObjectName("pieChartOption")
        self.pieChartOption.addItem("")
        self.pieChartOption.addItem("")
        self.pieChartOption.addItem("")
        self.pieChartOption.addItem("")
        
        self.chartInfo = QtWidgets.QLabel(self.menuOption)
        self.chartInfo.setGeometry(QtCore.QRect(650, 20, 47, 13))
        self.chartInfo.setTextFormat(QtCore.Qt.RichText)
        self.chartInfo.setObjectName("chartInfo")
        
        Statistik.setCentralWidget(self.menuOption)

        self.retranslateUi(Statistik)
        self.styleSheet(Statistik)
        self.sliderType.installEventFilter(self)
        self.statisticOption.installEventFilter(self)
        self.pieChartOption.installEventFilter(self)
        QtCore.QMetaObject.connectSlotsByName(Statistik)

    def retranslateUi(self, Statistik):
        _translate = QtCore.QCoreApplication.translate
        Statistik.setWindowTitle(_translate("Statistik", "MainWindow"))
        
        self.incomeInfo.setText(_translate("Statistik", "Jumlah Income"))
        self.IncomeValue.setText(_translate("Statistik", "Rp. X00.000"))
        self.outcomeInfo.setText(_translate("Statistik", "Jumlah Outcome"))
        self.outcomeValue.setText(_translate("Statistik", "Rp. X00.000"))
        
        self.statisticOption.setItemText(0, _translate("Statistik", "by day"))
        self.statisticOption.setItemText(1, _translate("Statistik", "by week"))
        self.statisticOption.setItemText(2, _translate("Statistik", "by month"))
        self.statisticOption.setItemText(3, _translate("Statistik", "by year"))
        self.statisticOption.setItemText(4, _translate("Statistik", "~~~~~~~"))
        self.statisticOption.setItemText(5, _translate("Statistik", "Save Graphic"))
        
        self.prevButton.setText(_translate("Statistik", "<"))
        self.nextButton.setText(_translate("Statistik", ">"))
        
        self.sliderType.setItemText(0, _translate("Statistik", "Daily"))
        self.sliderType.setItemText(1, _translate("Statistik", "Weekly"))
        self.sliderType.setItemText(2, _translate("Statistik", "Monthly"))
        self.sliderType.setItemText(3, _translate("Statistik", "Yearly"))
        
        self.statisticInfo.setText(_translate("Statistik", "Statistic"))
        self.timeInfo.setText(_translate("Statistik", "Statistic"))
        self.summaryInfo.setText(_translate("Statistik", "QuickView Summary"))
        self.newBalance.setText(_translate("Statistik", "New Balance"))
        self.prevBalance.setText(_translate("Statistik", "Previous Balance"))
        self.prevValue.setText(_translate("Statistik", "Rp. X00.000"))
        self.newValue.setText(_translate("Statistik", "Rp. X00.000"))
        self.changeValue.setText(_translate("Statistik", "+Rp. X0.000"))
        
        self.pieChartOption.setItemText(0, _translate("Statistik", "by total"))
        self.pieChartOption.setItemText(1, _translate("Statistik", "by category"))
        self.pieChartOption.setItemText(2, _translate("Statistik", "~~~~~~~~"))
        self.pieChartOption.setItemText(3, _translate("Statistik", "Save Graphic"))
        
        self.chartInfo.setText(_translate("Statistik", "Pie Chart"))

    def styleSheet(self, Statistik):
        iconDesign = """
            QComboBox {
                background-color: transparent;
                min-width: 20px;  /* Ukuran lebar combobox */
                min-height: 22px;
                padding: 0px;  /* Padding untuk memberikan jarak pada ikon */
            }
            QComboBox QAbstractItemView {
                min-width: 100px;
                max-width: 100px;
            }
            QComboBox::drop-down {
                width: 20px;  /* Ukuran tombol dropdown */
            }
            QComboBox::down-arrow {
                image: url(database.svg);  /* Ganti dengan ikon dropdown Anda */
                width: 20px;  /* Ukuran ikon dropdown */
                height: 20px;  /* Ukuran ikon dropdown */
            }
            QComboBox::item {
                height: 50px;  /* Menentukan tinggi item dalam combobox */
                font-size: 14px;  /* Ukuran font */
            }
            QComboBox::item:hover {
                background-color: lightgreen;  /* Warna latar belakang saat hover */
            }
            QComboBox::item:selected {
                background-color: lightblue;  /* Warna latar belakang saat item dipilih */
            }
            QComboBox::indicator {
                width: 30px;  /* Ukuran indicator (tombol dropdown) */
                height: 30px;
            }
            QComboBox::item:selected {
                color: transparent;  /* Menyembunyikan teks pada item yang dipilih */
            }
        """
        
        textDesign = """
        QLabel {
            font-size: 16px;             /* Sets font size */
            color: #FFFFFF;                 /* Sets text color */
            font-weight: bold;               /* Makes the font extra bold */
            }
        """

        chartDesign = """
            QFrame    {
            background-color: #191D24;
            border-radius: 15px; 
            border: 1px solid #7A9E5D; /* Optional: Adds a border with a slightly darker green */
            }
        """

        frameDesign = """
            QFrame    {
            background-color: #90B774;
            border-radius: 15px; 
            border: 1px solid #7A9E5D; /* Optional: Adds a border with a slightly darker green */
            }
        """
        
        Statistik.setStyleSheet("background-color: #252931;")
        
        self.incomeInfo.setStyleSheet(textDesign)
        self.outcomeInfo.setStyleSheet(textDesign)
        self.IncomeValue.setStyleSheet(textDesign)
        self.outcomeValue.setStyleSheet(textDesign)
        self.prevBalance.setStyleSheet(textDesign)
        self.newBalance.setStyleSheet(textDesign)

        self.Statistic.setStyleSheet(chartDesign)
        self.SliderButton.setStyleSheet("background-color: #252931;")
        self.pieChart.setStyleSheet(chartDesign)

        self.Summary.setStyleSheet(frameDesign)
        self.Income.setStyleSheet(frameDesign)
        self.Outcome.setStyleSheet(frameDesign)

        self.statisticOption.setStyleSheet(iconDesign)
        self.pieChartOption.setStyleSheet(iconDesign)
        
    def eventFilter(self, obj, event):
        # Memastikan hanya ComboBox yang scroll yang diblokir
        comboBox = [self.statisticOption, self.sliderType, self.pieChartOption]
        if obj in comboBox and event.type() == QtCore.QEvent.Wheel:
            return True  # Mencegah event scroll
        return super().eventFilter(obj, event)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Statistik = QtWidgets.QMainWindow()
    ui = Ui_Statistik()
    ui.setupUi(Statistik)
    Statistik.show()
    sys.exit(app.exec_())
