# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel, QStackedWidget, QGroupBox, QTextBrowser
from pages.view_wallet import WalletView
from pages.view_income import IncomeView
from pages.view_outcome import OutcomeView
from pages.view_history import HistoryView
from pages.view_category import CategoryView

def load_stylesheet(app, filename="styles/style.qss"):
    if os.path.exists(filename):
        with open(filename, "r") as file:
            qss = file.read()
            app.setStyleSheet(qss)
    else:
        print(f"Warning: Stylesheet {filename} not found!")

class Dashboard(QWidget):
    def __init__(self):
        super().__init__()
        self.init_ui(self)

    def init_ui(self, Form):
        Form.setObjectName("Money Tracker")
        Form.resize(1600, 900)

        self.stack = QStackedWidget(Form)

        # Halaman utama (Dashboard)
        self.main_menu = QWidget()

        self.wallet_view = WalletView(self.stack)
        self.income_view = IncomeView(self.stack)
        self.outcome_view = OutcomeView(self.stack)
        self.history_view = HistoryView(self.stack)
        self.category_view = CategoryView(self.stack)

        self.init_main_menu(Form)
        self.stack.addWidget(self.main_menu)
        self.stack.addWidget(self.wallet_view)
        self.stack.addWidget(self.income_view)
        self.stack.addWidget(self.outcome_view)
        self.stack.addWidget(self.history_view)
        self.stack.addWidget(self.category_view)

        main_layout = QVBoxLayout()
        main_layout.addWidget(self.stack)
        Form.setLayout(main_layout)

    def init_main_menu(self, Form):
        self.main_menu = QWidget()
        main_menu_layout = QVBoxLayout()


        self.HomeSection = QGroupBox(Form)
        self.HomeSection.setGeometry(QtCore.QRect(0, 0, 357, 905))
        self.HomeSection.setObjectName("HomeSection")

        self.btn_home = QPushButton(self.HomeSection)
        self.btn_home.setGeometry(QtCore.QRect(30, 30, 290, 150))
        icon0 = QtGui.QIcon()
        icon0.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/logo-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon0)
        self.btn_home.setIconSize(QtCore.QSize(80, 80))
        self.btn_home.setObjectName("btn_home")
        self.btn_home.clicked.connect(lambda: self.stack.setCurrentWidget(self.main_menu))

        self.btn_income = QPushButton(self.HomeSection)
        self.btn_income.setGeometry(QtCore.QRect(30, 191, 290, 76))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/add-income.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_income.setIcon(icon)
        self.btn_income.setIconSize(QtCore.QSize(55, 61))
        self.btn_income.setObjectName("btn_homeSection")
        self.btn_income.clicked.connect(lambda: (
            self.income_view.refresh_combobox(),
            self.stack.setCurrentWidget(self.income_view)
        ))


        self.btn_outcome = QPushButton(self.HomeSection)
        self.btn_outcome.setGeometry(QtCore.QRect(30, 276, 290, 76))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/add-outcome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_outcome.setIcon(icon1)
        self.btn_outcome.setIconSize(QtCore.QSize(55, 61))
        self.btn_outcome.setObjectName("btn_homeSection")
        self.btn_outcome.clicked.connect(lambda: (
            self.outcome_view.refresh_combobox(), 
            self.stack.setCurrentWidget(self.outcome_view)
        ))


        self.btn_wallet = QPushButton(self.HomeSection)
        self.btn_wallet.setGeometry(QtCore.QRect(30, 362, 290, 76))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/wallet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wallet.setIcon(icon2)
        self.btn_wallet.setIconSize(QtCore.QSize(55, 61))
        self.btn_wallet.setObjectName("btn_homeSection")
        self.btn_wallet.clicked.connect(lambda: (
            self.wallet_view.load_wallets(),
            self.stack.setCurrentWidget(self.wallet_view)
        ))

        self.btn_history = QPushButton(self.HomeSection)
        self.btn_history.setGeometry(QtCore.QRect(30, 447, 290, 76))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_history.setIcon(icon3)
        self.btn_history.setIconSize(QtCore.QSize(55, 61))
        self.btn_history.setObjectName("btn_homeSection")
        self.btn_history.clicked.connect(lambda: (
            self.history_view.load_data("all"),
            self.history_view.radio_all.setChecked(True),
            self.stack.setCurrentWidget(self.history_view)
        ))

        self.btn_statistic = QPushButton(self.HomeSection)
        self.btn_statistic.setGeometry(QtCore.QRect(30, 532, 290, 76))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/statistic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_statistic.setIcon(icon4)
        self.btn_statistic.setIconSize(QtCore.QSize(55, 61))
        self.btn_statistic.setObjectName("btn_homeSection")

        self.btn_category = QPushButton(self.HomeSection)
        self.btn_category.setGeometry(QtCore.QRect(30, 617, 290, 76))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/category.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_category.setIcon(icon5)
        self.btn_category.setIconSize(QtCore.QSize(55, 61))
        self.btn_category.setObjectName("btn_homeSection")
        self.btn_category.clicked.connect(lambda: self.stack.setCurrentWidget(self.category_view))


        self.btn_wishlist = QPushButton(self.HomeSection)
        self.btn_wishlist.setGeometry(QtCore.QRect(30, 702, 290, 76))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/wishlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wishlist.setIcon(icon6)
        self.btn_wishlist.setIconSize(QtCore.QSize(55, 61))
        self.btn_wishlist.setObjectName("btn_homeSection")

        self.aboutUs = QPushButton(self.HomeSection)
        self.aboutUs.setGeometry(QtCore.QRect(32, 820, 59, 59))
        self.aboutUs.setStyleSheet("background-color: #121D2C;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/aboutUs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutUs.setIcon(icon7)
        self.aboutUs.setIconSize(QtCore.QSize(55, 61))
        self.aboutUs.setObjectName("btn_aboutUs")

        self.label = QLabel(self.HomeSection)
        self.label.setGeometry(QtCore.QRect(250, 844, 61, 41))
        self.label.setToolTipDuration(-1)
        self.label.setStyleSheet("color: white;\n"
"background-color: #121D2C;")
        self.label.setObjectName("label")

        self.Container = QStackedWidget(self.main_menu)
        self.Container.setGeometry(QtCore.QRect(340, 0, 1263, 900))
        self.Container.setObjectName("Container")

        self.groupBox_1 = QGroupBox(self.Container)
        self.groupBox_1.setGeometry(QtCore.QRect(61, 40, 498, 218))
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox")

        self.groupBox_2 = QGroupBox(self.Container)
        self.groupBox_2.setGeometry(QtCore.QRect(61, 283, 498, 561))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox")

        self.groupBox_3 = QGroupBox(self.Container)
        self.groupBox_3.setGeometry(QtCore.QRect(581, 40, 638, 502))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox")

        self.groupBox_4 = QGroupBox(self.Container)
        self.groupBox_4.setGeometry(QtCore.QRect(581, 564, 638, 280))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # self.btn_home.setText(_translate("Form", " Home"))
        self.btn_income.setText(_translate("Form", " Edit Income"))
        self.btn_outcome.setText(_translate("Form", " Edit Outcome"))
        self.btn_wallet.setText(_translate("Form", " Wallet"))
        self.btn_history.setText(_translate("Form", " History"))
        self.btn_statistic.setText(_translate("Form", " Statistic"))
        self.btn_category.setText(_translate("Form", " Category"))
        self.btn_wishlist.setText(_translate("Form", " Wishlist"))
        self.label.setText(_translate("Form", "v1.2"))
