# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel, QStackedWidget
from view_wallet import WalletView
from view_income import IncomeView
from view_outcome import OutcomeView
from view_history import HistoryView
from view_category import CategoryView

def load_stylesheet(app, filename="styles/style.qss"):
    with open(filename, "r") as file:
        qss = file.read()
        app.setStyleSheet(qss)

class Dashboard(object):
    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 900)


        self.stack = QStackedWidget(self)
        

        # Halaman utama (Dashboard)
        self.main_menu = QWidget()

        self.wallet_view = WalletView(self.stack)
        self.income_view = IncomeView(self.stack)
        self.outcome_view = OutcomeView(self.stack)
        self.history_view = HistoryView(self.stack)
        self.category_view = CategoryView(self.stack)




        self.Container = QtWidgets.QGroupBox(Form)
        self.Container.setGeometry(QtCore.QRect(340, 0, 1263, 900))
        self.Container.setObjectName("Container")

        self.groupBox = QtWidgets.QGroupBox(self.Container)
        self.groupBox.setGeometry(QtCore.QRect(61, 40, 498, 218))
        self.groupBox.setStyleSheet("background-color: #98C379;\n"
"border-radius: 25%;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Container)
        self.groupBox_3.setGeometry(QtCore.QRect(61, 283, 498, 561))
        self.groupBox_3.setStyleSheet("background-color: #98C379;\n"
"border-radius: 25%;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Container)
        self.groupBox_4.setGeometry(QtCore.QRect(581, 40, 638, 502))
        self.groupBox_4.setStyleSheet("background-color: #98C379;\n"
"border-radius: 25%;\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Container)
        self.groupBox_5.setGeometry(QtCore.QRect(581, 564, 638, 280))
        self.groupBox_5.setStyleSheet("background-color: #98C379;\n"
"border-radius: 25%;\n"
"")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(140, 220, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")

        self.HomeSection = QtWidgets.QGroupBox(Form)
        self.HomeSection.setGeometry(QtCore.QRect(-5, 0, 357, 905))
        self.HomeSection.setObjectName("HomeSection")

        self.logoApp = QtWidgets.QTextBrowser(self.HomeSection)
        self.logoApp.setGeometry(QtCore.QRect(30, 30, 290, 150))
        self.logoApp.setObjectName("logoApp")

        self.btn_income = QtWidgets.QPushButton(self.HomeSection)
        self.btn_income.setGeometry(QtCore.QRect(30, 191, 290, 76))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/add-income.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_income.setIcon(icon)
        self.btn_income.setIconSize(QtCore.QSize(55, 61))
        self.btn_income.setObjectName("btn_homeSection")
        self.btn_income.clicked.connect(lambda: (
            self.income_view.refresh_combobox(),
            self.stack.setCurrentWidget(self.income_view)
        ))

        self.btn_outcome = QtWidgets.QPushButton(self.HomeSection)
        self.btn_outcome.setGeometry(QtCore.QRect(30, 276, 290, 76))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/add-outcome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_outcome.setIcon(icon1)
        self.btn_outcome.setIconSize(QtCore.QSize(55, 61))
        self.btn_outcome.setObjectName("btn_homeSection")
        self.btn_outcome.clicked.connect(lambda: (
            self.outcome_view.refresh_combobox(), 
            self.stack.setCurrentWidget(self.outcome_view)
        ))


        self.btn_wallet = QtWidgets.QPushButton(self.HomeSection)
        self.btn_wallet.setGeometry(QtCore.QRect(30, 362, 290, 76))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/wallet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wallet.setIcon(icon2)
        self.btn_wallet.setIconSize(QtCore.QSize(55, 61))
        self.btn_wallet.setObjectName("btn_homeSection")
        self.btn_wallet.clicked.connect(lambda: (
            self.wallet_view.load_wallets(),
            self.stack.setCurrentWidget(self.wallet_view)
        ))

        self.btn_history = QtWidgets.QPushButton(self.HomeSection)
        self.btn_history.setGeometry(QtCore.QRect(30, 447, 290, 76))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_history.setIcon(icon3)
        self.btn_history.setIconSize(QtCore.QSize(55, 61))
        self.btn_history.setObjectName("btn_homeSection")
        self.btn_history.clicked.connect(lambda: (
            self.history_view.load_data("all"),
            self.history_view.radio_all.setChecked(True),
            self.stack.setCurrentWidget(self.history_view)
        ))

        self.btn_statistic = QtWidgets.QPushButton(self.HomeSection)
        self.btn_statistic.setGeometry(QtCore.QRect(30, 532, 290, 76))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/statistic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_statistic.setIcon(icon4)
        self.btn_statistic.setIconSize(QtCore.QSize(55, 61))
        self.btn_statistic.setObjectName("btn_homeSection")

        self.btn_category = QtWidgets.QPushButton(self.HomeSection)
        self.btn_category.setGeometry(QtCore.QRect(30, 617, 290, 76))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/category.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_category.setIcon(icon5)
        self.btn_category.setIconSize(QtCore.QSize(55, 61))
        self.btn_category.setObjectName("btn_homeSection")
        self.category.clicked.connect(lambda: self.stack.setCurrentWidget(self.category_view))


        self.btn_wishlist = QtWidgets.QPushButton(self.HomeSection)
        self.btn_wishlist.setGeometry(QtCore.QRect(30, 702, 290, 76))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_wishlist.setFont(font)
        
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/wishlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wishlist.setIcon(icon6)
        self.btn_wishlist.setIconSize(QtCore.QSize(55, 61))
        self.btn_wishlist.setObjectName("btn_homeSection")
        self.btn_wishlist = QtWidgets.QPushButton(self.HomeSection)
        self.btn_wishlist.setGeometry(QtCore.QRect(22, 820, 59, 59))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_wishlist.setFont(font)
        self.btn_wishlist.setStyleSheet("background-color: #121D2C;")
        self.btn_wishlist.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../money-tracker/img/icon/aboutUs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wishlist.setIcon(icon7)
        self.btn_wishlist.setIconSize(QtCore.QSize(55, 61))
        self.btn_wishlist.setObjectName("wishlist_8")
        self.label = QtWidgets.QLabel(self.HomeSection)
        self.label.setGeometry(QtCore.QRect(250, 844, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setToolTipDuration(-1)
        self.label.setStyleSheet("color: white;\n"
"background-color: #121D2C;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.btn_income.setText(_translate("Form", " Edit Income"))
        self.btn_outcome.setText(_translate("Form", " Edit Outcome"))
        self.btn_wallet.setText(_translate("Form", " Wallet"))
        self.btn_history.setText(_translate("Form", " History"))
        self.btn_statistic.setText(_translate("Form", " Statistic"))
        self.btn_category.setText(_translate("Form", " Category"))
        self.btn_wishlist.setText(_translate("Form", " Wishlist"))
        self.label.setText(_translate("Form", "v1.2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    load_stylesheet(app) # Load Stylesheet
    Form = QtWidgets.QWidget()
    ui = Dashboard()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
