# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controller.otp import Otp
from controller.account import Account


class PemulihanScreen(QtWidgets.QWidget):
    def __init__(self, stack, key_dict):
        super().__init__()
        self.stack = stack
        self.key_dict = key_dict
        self.otp_backend = Otp()
        self.pemulihan_Ui()

    def pemulihan_Ui(self):
        self.setGeometry(0, 0, 360, 640)
        self.setStyleSheet("background-color: #1c1f26; color: #d3e9a3;")
        
        # Layout utama
        main_layout = QtWidgets.QVBoxLayout()
        main_layout.setContentsMargins(20, 20, 20, 20)
        main_layout.setSpacing(20)
        
        # Header
        header_layout = QtWidgets.QHBoxLayout()
        
        # Tombol Kembali
        self.back_button = QtWidgets.QPushButton("←")
        self.back_button.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                color: #d3e9a3;
                font-size: 20px;
                border: none;
            }
        """)
        self.back_button.clicked.connect(lambda: self.stack.setCurrentIndex(self.stack.currentIndex() - 1))
        header_layout.addWidget(self.back_button)
        
        header_layout.addStretch()
        main_layout.addLayout(header_layout)
        
        # Judul
        title_label = QtWidgets.QLabel("Pemulihan Password")
        title_label.setStyleSheet("font-size: 24px; font-weight: bold;")
        title_label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(title_label)
        
        # Deskripsi
        desc_label = QtWidgets.QLabel("Masukan E-mail anda yang telah terdaftar")
        desc_label.setStyleSheet("font-size: 16px;")
        desc_label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(desc_label)
        
        # Input Email
        email_layout = QtWidgets.QVBoxLayout()
        
        email_label = QtWidgets.QLabel("Email")
        email_label.setStyleSheet("font-size: 14px;")
        email_layout.addWidget(email_label)
        
        self.email_input = QtWidgets.QLineEdit()
        self.email_input.setStyleSheet("""
            QLineEdit {
                background-color: #2c2f36;
                color: #d3e9a3;
                border: 1px solid #3c3f46;
                border-radius: 5px;
                padding: 8px;
            }
        """)
        self.email_input.setPlaceholderText("Masukkan email terdaftar")
        email_layout.addWidget(self.email_input)
        
        main_layout.addLayout(email_layout)
        
        # Input OTP
        otp_layout = QtWidgets.QVBoxLayout()
        
        otp_label = QtWidgets.QLabel("Kode OTP")
        otp_label.setStyleSheet("font-size: 14px;")
        otp_layout.addWidget(otp_label)
        
        self.otp_input = QtWidgets.QLineEdit()
        self.otp_input.setStyleSheet("""
            QLineEdit {
                background-color: #2c2f36;
                color: #d3e9a3;
                border: 1px solid #3c3f46;
                border-radius: 5px;
                padding: 8px;
            }
        """)
        self.otp_input.textChanged.connect(self.recover_password)
        self.otp_input.setPlaceholderText("Masukkan kode OTP")
        otp_layout.addWidget(self.otp_input)
        
        main_layout.addLayout(otp_layout)
        
        # Pesan bantuan
        help_label = QtWidgets.QLabel("Password dan OTP akan dikirimkan ke email anda.\n"
                                     "Jika pesan tidak terkirim, harap cek folder spam\n"
                                     "di email anda atau kirim ulang kode OTP")
        help_label.setStyleSheet("font-size: 12px; color: #8c8c8c;")
        help_label.setAlignment(QtCore.Qt.AlignCenter)
        help_label.setWordWrap(True)
        main_layout.addWidget(help_label)
        
        # Timer label
        self.timer_label = QtWidgets.QLabel()
        self.timer_label.setStyleSheet("font-size: 12px; color: #8c8c8c;")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.hide()
        main_layout.addWidget(self.timer_label)
        
        # Tombol Lanjut
        button_layout = QtWidgets.QHBoxLayout()
        
        self.send_otp_button = QtWidgets.QPushButton("Kirim Kode")
        self.send_otp_button.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                color: #7db16e;
                border: none;
                font-size: 14px;
            }
        """)
        self.send_otp_button.clicked.connect(self.send_otp)
        button_layout.addWidget(self.send_otp_button)
        
        button_layout.addStretch()
        
        self.recover_button = QtWidgets.QPushButton("Pulihkan Password")
        self.recover_button.setEnabled(False)
        self.recover_button.setStyleSheet("""
            QPushButton {
                background-color: #7db16e;
                color: #1c1f26;
                border: none;
                border-radius: 5px;
                padding: 10px;
                font-weight: bold;
            }
        """)
        self.recover_button.clicked.connect(self.stack.setCurrentIndex(self.stack.currentIndex() + 1))
        button_layout.addWidget(self.recover_button)
        
        main_layout.addLayout(button_layout)
        
        main_layout.addStretch()
        self.setLayout(main_layout)
        
        # Timer
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_cooldown)

    def new_password_UI(self):
        self.setGeometry(0, 0, 360, 640)
        self.setStyleSheet("background-color: #1c1f26; color: #d3e9a3;")
        
        # Layout utama
        main_layout = QtWidgets.QVBoxLayout()
        main_layout.setContentsMargins(20, 20, 20, 20)
        main_layout.setSpacing(20)
        
        # Header
        header_layout = QtWidgets.QHBoxLayout()
        
        # Tombol Kembali
        self.back_button = QtWidgets.QPushButton("←")
        self.back_button.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                color: #d3e9a3;
                font-size: 20px;
                border: none;
            }
        """)
        self.back_button.clicked.connect(lambda: self.stack.setCurrentIndex(self.stack.currentIndex() - 1))
        header_layout.addWidget(self.back_button)
        
        header_layout.addStretch()
        main_layout.addLayout(header_layout)
        
        # Judul
        title_label = QtWidgets.QLabel("Pemulihan Password")
        title_label.setStyleSheet("font-size: 24px; font-weight: bold;")
        title_label.setAlignment(QtCore.Qt.AlignCenter)
        main_layout.addWidget(title_label)

    def update_cooldown(self):
        cooldown_active, remaining_time = self.otp_backend.is_cooldown_active()
        if cooldown_active:
            self.timer_label.setText(f"Harap tunggu {remaining_time} detik sebelum mengirim OTP lagi")
            self.timer_label.show()
            self.send_otp_button.setEnabled(False)
        else:
            self.timer_label.hide()
            self.send_otp_button.setEnabled(True)
            self.timer.stop()

    def send_otp(self):
        email = self.email_input.text()
        if email:
            key_dict = {"key": ""}  # Key akan diisi oleh controller
            if self.otp_backend.startsmtp(email, key_dict):
                self.timer.start(1000)
                self.back_button.setEnabled(False)

    def recover_password(self):
        email = self.email_input.text()
        otp = self.otp_input.text()
        if email and otp:
            result = self.otp_backend.otpcheck(otp, self.key_dict["key"])
            if result:
                # Lanjutkan ke halaman pemulihan password
                self.recover_button.setStyleSheet("""
                    QPushButton {
                        background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #7db16e, stop:1 #b8e994);
                        color: #1c1f26;
                        border: none;
                        border-radius: 5px;
                        padding: 10px;
                        font-weight: bold;
                    }
                """)
                self.recover_button.setEnabled(True)
            else:
                QtWidgets.QMessageBox.warning(self, "Error", "Kode OTP tidak valid.")
